services:
  jaeger-agent:
    image: jaegertracing/all-in-one:1.62
    command: ["--memory.max-traces=50000"]
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      # - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
