name: SocialNet-Repl-Resilience

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bench:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    strategy:
      matrix:
        worker: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4

      - name: Free space
        run: |
          sudo rm -rf /opt/hostedtoolcache /usr/local/lib/android || true

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install specific Docker version
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker --version

      - uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Make scripts executable
        run: chmod +x $(git ls-files '*.sh')

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy networkx scipy  

      - name: Run replicated pipeline (worker ${{ matrix.worker }})
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          BASE_SEED: ${{ matrix.worker }}
        run: |
          chmod +x pipeline_repl.sh
          ./pipeline_repl.sh --seed "$BASE_SEED"

      - name: Upload replicated results (worker ${{ matrix.worker }})
        if: ${{ always() }}  
        uses: actions/upload-artifact@v4
        with:
          name: replicated-resilience-results-${{ matrix.worker }}
          path: DeathStarBench/socialNetwork/results/repl/*.json
  
